dataset_csv_filename: quotes.csv
df_filepath: src/quotes.csv
hours_to_wait_before_recheck: 4
kaggle_dataset_api_cmd: kaggle datasets download -d manann/quotes-500k
last_notified_date: '2024-08-29'
program_batfilename: main.bat
