dataset_csv_filename: quotes.csv
hadith_df_filepath: src/hadiths_with_source.csv
hours_to_wait_before_recheck: 4
kaggle_dataset_api_cmd: kaggle datasets download -d manann/quotes-500k
last_notified_date: '2024-09-30'
program_batfilename: main.bat
quote_df_filepath: src/quotes.csv
